### ISSUE TITLE
Please explain how to deploy app seeded like this

### ISSUE THREAD

**Issue by BesuglovS** [mschwarzmueller/angular2-seed#4]
I must have been missed my gulp & SystemJS training.
It seems like index -referenced node modules + bundle.js + src folder is not enough.
Sorry for a complete-starter question.

**Comment by BesuglovS** [comment]
Sorry for such a newbie request :-)

**Comment by mschwarzmueller** [comment]
Hi, you should deploy the whole dist/ folder when using the experimental branch, that should make it work.
The master branch will be updated in the future, there deployment requires a bit more work, so I'd use the experimental one
